---
title: "Problem Set 6"
author: "Dimple Kanadia"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
#Import required packages
knitr::opts_chunk$set(echo = TRUE)
library(flexdashboard)
library(shiny)
library(plotly)
library(rmarkdown)
library(DT)
##Load data CT_Inmate_Data
ct <- read.csv2(file="CT_inmate_data.csv",header=TRUE, sep=",")
```


Column {data-width=650}
-----------------------------------------------------------------------
### Chart A
```{r , echo=TRUE}
## Tabular display of sample records of CT_Inmate_Data
cts<- ct[1:100,c(3,7,8,9)]
DT::datatable(cts, options = list(
  bPaginate = FALSE
))
```

Column {data-width=250}
-----------------------------------------------------------------------
### Chart B
```{r , echo=TRUE}
##Gauge to distribute CT_Inmate_Data based on AGE group
## ELEDERLY
ct <- read.csv2(file="/Users/dimplekanadia/CT_inmate_data.csv",header=TRUE, sep=",")
elderly <- ct$AGE
gauge(elderly, min = 0, max = 100, symbol = '%', gaugeSectors(
  success = c(51,60), warning = c(61, 79), danger = c(80, 100)
))
##AVERAGE
average <- ct$AGE
gauge(average, min = 0, max = 50,symbol = '%', gaugeSectors(
  success = c(26,30), warning = c(31, 40), danger = c(41, 50)
))
##YOUTH
youth <- ct$AGE
gauge(youth, min = 0, max = 25, symbol = '%',gaugeSectors(
  success = c(10, 15), warning = c(16, 20), danger = c(20, 25)
))
```

Column {data-width=450}
-----------------------------------------------------------------------
### Chart C
```{r, echo=TRUE}
###Pie Chart to display CT_Inmate_Data for RACE and AGE
plot_ly(ct, labels = RACE, values = AGE, type = "pie") %>%
  layout(title = "Racial Percentage Distribution of Inmates in CT")
```